spring:
  artemis:
    mode: embedded
    embedded:
      queues: prospring6
      enabled: true

# Logging config
logging:
  pattern:
    console: "%-5level: %class{0} - %msg%n"
  level:
    root: INFO
    org.springframework: INFO
    com.apress.prospring6.thirteen: INFO
    #logging.level.org.apache.activemq.audit.base: WARN
    #logging.level.org.apache.activemq.audit.message: WARN