spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/musicdb?useSSL=false
    username: prospring6
    password: prospring6
    hikari:
      auto-commit: true
  jooq:
    sql-dialect: mariadb

# Logging config
logging:
  pattern:
    console: "%-5level: %class{0} - %msg%n"
  level:
    root: INFO
    org.springframework.boot: INFO
    com.apress.prospring6.seven: INFO
    org.jooq: INFO