# Configuring info endpoint
info:
  app:
    name: chapter18-boot
    description: "Pro Spring 6 - Chapter 18 :: Spring Actuator Application"
    version: 6.0-SNAPSHOT
  author: "Iuliana Cosmina"

server:
  port: 8081
  servlet:
    context-path: /
  compression:
    enabled: true # improves website performance by compressing response body
  address: 0.0.0.0


spring:
  info:
    build:
      encoding: UTF-8
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/musicdb?useSSL=false
    username: prospring6
    password: prospring6
    hikari:
      maximum-pool-size: 25
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          batch_size: 10
          fetch_size: 30
        max_fetch_depth: 3
        show-sql: true
        format-sql: false
        use_sql_comments: false
        hbm2ddl:
          auto: none
# enabling Actuator endpoints over JMX
  jmx:
    enabled: true
    default-domain: jmxBootDemo
management:
  info:
    java:
      enabled: true
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      domain: jmxBootDemo
      exposure:
        include: "*"
    web:
      path-mapping:
        health: salud
      exposure:
        include: "*"
      base-path: /monitoring
  server:
    port: 9091
    #address: 127.0.0.1

# Logging config
logging:
  pattern:
    console: "%-5level: %class{0} - %msg%n"
  level:
    root: INFO
    org.springframework.boot: DEBUG
    com.apress.prospring6.fifteen: INFO

